import Vue from 'vue'

import '@mdi/font/css/materialdesignicons.min.css'
import 'vuetify/dist/vuetify.min.css'
import color from 'vuetify/lib/util/colors'

import Vuetify, {
    VApp,
    VCol,
    VRow,
    VCard,
    VCardText,
    VCardTitle,
    VCardSubtitle,
    VCardActions,
    VBtn,
    VAppBar,
    VAppBarNavIcon,
    VContainer,
    VNavigationDrawer,
    VDivider,
    VList,
    VListItem,
    VListItemIcon,
    VListItemTitle,
    VListItemGroup,
    VIcon,
    VListItemAvatar,
    VImg,
    VListItemContent,
    VListItemSubtitle,
    VListItemAction,
    VToolbar,
    VToolbarTitle,
    VMenu,
    VSimpleTable,
    VPagination,
    VSelect,
    VSwitch,
    VTextField,
    VBadge,
    VSpacer,
    VBottomNavigation,
    VFooter,
    VMain,
    VCarousel,
    VCarouselItem,
    VTabs,
    VTab,
    VTabItem,
    VHover,
    VTreeview,
    VCheckbox,
    VBreadcrumbs,
    VExpandTransition,
    VRating,
    VRadioGroup,
    VRadio,
    
    
} from 'vuetify/lib'

Vue.use(Vuetify, {
    components: {
        VApp,
        VCol,
        VRow,
        VCard,
        VCardText,
        VCardTitle,
        VCardSubtitle,
        VCardActions,
        VBtn,
        VAppBar,
        VAppBarNavIcon,
        VContainer,
        VNavigationDrawer,
        VDivider,
        VList,
        VListItem,
        VListItemIcon,
        VListItemTitle,
        VListItemGroup,
        VIcon,
        VListItemAvatar,
        VImg,
        VListItemContent,
        VListItemSubtitle,
        VListItemAction,
        VToolbar,
        VToolbarTitle,
        VMenu,
        VSimpleTable,
        VPagination,
        VSelect,
        VSwitch,
        VTextField,
        VBadge,
        VSpacer,
        VBottomNavigation,
        VFooter,
        VMain,
        VCarousel,
        VCarouselItem,
        VTabs,
        VTab,
        VTabItem,
        VHover,
        VTreeview,
        VCheckbox,
        VBreadcrumbs,
        VExpandTransition,
        VRating,
        VRadioGroup,
        VRadio,
        
    }
})

export default new Vuetify({
    icons: {
        iconfont: 'mdi'
    },
    theme: {
        dark: false,
    },
    themes: {
        light: {
            primary: '#2D3753',
            secondary: '#2D3753',
            accent: '#3AE3D6',
            error: '#f44336',
            info: '#2d3753',
            success: '#7a904a',
            warning: '#f78012',
            accent: "#8c9eff",
        },
    },
})